// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP0DNsCoYDLpBaqQ7e0ExSXup0-M5hDB4',
    appId: '1:759312443189:web:4b908e52c47b910951ce7c',
    messagingSenderId: '759312443189',
    projectId: 'neuronudge-d1e18',
    authDomain: 'neuronudge-d1e18.firebaseapp.com',
    storageBucket: 'neuronudge-d1e18.firebasestorage.app',
    measurementId: 'G-103R4RX4GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbQ4HFyAlmrV8zytQg3i-0v57-FyVmwg',
    appId: '1:759312443189:android:1bf4ec905e24dacd51ce7c',
    messagingSenderId: '759312443189',
    projectId: 'neuronudge-d1e18',
    storageBucket: 'neuronudge-d1e18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJOsiUQjuvx6bMD54MCJiHtE8zjrHAoEE',
    appId: '1:759312443189:ios:baebef18427b714851ce7c',
    messagingSenderId: '759312443189',
    projectId: 'neuronudge-d1e18',
    storageBucket: 'neuronudge-d1e18.firebasestorage.app',
    iosClientId: '759312443189-0i5ffjnfkf2r0d42r0qkarosv4soifrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJOsiUQjuvx6bMD54MCJiHtE8zjrHAoEE',
    appId: '1:759312443189:ios:baebef18427b714851ce7c',
    messagingSenderId: '759312443189',
    projectId: 'neuronudge-d1e18',
    storageBucket: 'neuronudge-d1e18.firebasestorage.app',
    iosClientId: '759312443189-0i5ffjnfkf2r0d42r0qkarosv4soifrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP0DNsCoYDLpBaqQ7e0ExSXup0-M5hDB4',
    appId: '1:759312443189:web:f0503546656778d551ce7c',
    messagingSenderId: '759312443189',
    projectId: 'neuronudge-d1e18',
    authDomain: 'neuronudge-d1e18.firebaseapp.com',
    storageBucket: 'neuronudge-d1e18.firebasestorage.app',
    measurementId: 'G-7650H6F3GC',
  );
}
